### ISSUE TITLE
how to build in Ubuntu 16.04

### ISSUE THREAD

**Issue by ginharu** [BeamMW/beam#461]
i want to build beam in Ubuntu 16.04

**Comment by mikeyb** [comment]
And you have tried the build docs linked from the README.md?  https://github.com/BeamMW/beam/wiki/How-to-build

**Comment by ginharu** [comment]
> And you have tried the build docs linked from the README.md? https://github.com/BeamMW/beam/wiki/How-to-build

This is in Ubuntu 14.04，it can't build in Ubuntu 16.04

**Comment by mikeyb** [comment]
I built it fine from those instructions. Have you tried? If so, what problem do you run into? Again, it builds perfectly fine on 16.04

**Comment by ginharu** [comment]
> 我从这些指示中建立得很好。你有没有尝试过？如果是这样，你遇到什么问题？再次，它在16.04完美地构建
> [...](#)
> 在2019年2月21日02:49，ginharu ***@***.***>写道：您是否尝试过从README.md链接的构建文档？https://github.com/BeamMW/beam/wiki/How-to-build 这是在Ubuntu 14.04中，它无法在Ubuntu 16.04中构建 - 您收到此消息是因为您评论过。直接回复此电子邮件，在GitHub上查看，或将该线程静音。

[ 92%] Building CXX object ui/CMakeFiles/beam-wallet-ui.dir/viewmodel/wallet_view.cpp.o
[ 92%] Building CXX object ui/CMakeFiles/beam-wallet-ui.dir/viewmodel/ui_helpers.cpp.o
[ 92%] Building CXX object ui/CMakeFiles/beam-wallet-ui.dir/viewmodel/messages_view.cpp.o
/data/coin/beam/beam/ui/viewmodel/ui_helpers.cpp: In function ‘QString beamui::BeamToString(const Amount&)’:
/data/coin/beam/beam/ui/viewmodel/ui_helpers.cpp:21:70: error: ‘FloatingPointShortest’ is not a member of ‘QLocale’
         QString qstr = QLocale().toString(real_amount, 'f', QLocale::FloatingPointShortest);
                                                                      ^~~~~~~~~~~~~~~~~~~~~
ui/CMakeFiles/beam-wallet-ui.dir/build.make:347: recipe for target 'ui/CMakeFiles/beam-wallet-ui.dir/viewmodel/ui_helpers.cpp.o' failed
make[2]: *** [ui/CMakeFiles/beam-wallet-ui.dir/viewmodel/ui_helpers.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/data/coin/beam/beam/ui/viewmodel/wallet_view.cpp: In member function ‘void WalletViewModel::onGeneratedNewAddress(const beam::WalletAddress&)’:
/data/coin/beam/beam/ui/viewmodel/wallet_view.cpp:812:31: error: variable ‘QColor color’ has initializer but incomplete type
         QColor color(Qt::white);
                               ^
ui/CMakeFiles/beam-wallet-ui.dir/build.make:282: recipe for target 'ui/CMakeFiles/beam-wallet-ui.dir/viewmodel/wallet_view.cpp.o' failed


I made a mistake building here, I don't know what the problem is

**Comment by gingervik** [comment]
@nesbox please, help

**Comment by mikeyb** [comment]
Sounds like you dont have all the requirements installed for QT

If you add this to your cmake command does it build:

`-DBEAM_NO_QT_UI_WALLET=On`

**Comment by nesbox** [comment]
@ginharu seems you have installed the wrong QT version, we used QT >= 5.11

**Comment by gingervik** [comment]
long time no response from user
